version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      # Enable docker https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
      
  build:
    commands:
      - sam build --use-container --template template.yaml
      - . ./assume-role.sh "arn:aws:iam::632178947285:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-ozbWnHlFcrvu" test-package
      - sam package --s3-bucket aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-zaatxq65ywz9
                    --region us-east-2
                    --output-template-file packaged-test.yaml
      
artifacts:
  files:
    - packaged-test.yaml
    - assume-role.sh
    - pipeline/*
